config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :companies
  resources :posts
  root 'pages#show'
  get 'pages/show'
  post '/callback' => 'line_events#callback'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :company, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end
end

app/controllers/line_events_controller.rb
class LineEventsController < ApplicationController
  require 'line/bot'

  protect_from_forgery :except => [:callback]

  def client
    @client ||= Line::Bot::Client.new do |config|
      config.channel_secret = ENV['LINE_CHANNEL_SECRET']
      config.channel_token = ENV['LINE_CHANNEL_TOKEN']
    end
  end

  def callback
    body = request.body.read

    signature = request.env['HTTP_X_LINE_SIGNATURE']
    unless client.validate_signature(body, signature)
      head :bad_request
    end

    events = client.parse_events_from(body)

    events.each do |event|
      line_user_id = event['source']['userId']
      user = User.find_by(line_user_id: line_user_id)
      case event
      when Line::Bot::Event::Follow
        if user.nil?
          User.create!(line_user_id: line_user_id, status: 0)
          client.reply_message(event['replyToken'], want_company_code)
        elsif user.status == 0
          client.reply_message(event['replyToken'], want_company_code)
        end
      when Line::Bot::Event::Message
        case user.status
        when 0 # company_code未登録
          code = event.message['text']
          company = Company.find_by(company_code: code)
          if company.nil?
            client.reply_message(event['replyToken'], compnay_not_found)
          else
            company.users.append(user)
            user.update(status: 1)
            client.reply_message(event['replyToken'], want_user_name)
          end
        when 1 # name未登録
          user.name = event.message['text']
          if user.save
            user.update(status: 2)
            client.reply_message(event['replyToken'], user_name_saved)
          else
            client.reply_message(event['replyToken'], invalid_user_name)
          end
        end
      when Line::Bot::Event::Postback
        weather = event['postback']['data']
        client.reply_message(event['replyToken'], answer_accepted(weather))
      end
    end

    head :ok
  end

  private

  def want_company_code
    {
      'type': 'text',
      'text': '会社コードを入力してください。'
    }
  end

  def want_user_name
    {
      'type': 'text',
      'text': 'あなたのお名前を入力してください。'
    }
  end

  def compnay_not_found
    {
      'type': 'text',
      'text': '入力された会社コードは無効です。'
    }
  end

  def user_name_saved
    {
      'type': 'text',
      'text': 'お名前を登録しました。'
    }
  end

  def invalid_user_name
    {
      'type': 'text',
      'text': '入力された名前は無効です。'
    }
  end

  def answer_accepted(weather)
    {
      'type': 'text',
      'text': '回答ありがとうございます：' + weather
    }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def update
    user = User.find(params[:id])
    message = {
      "type": "template",
      "altText": "定期アンケート",
      "template": {
        "type": "buttons",
        "imageAspectRatio": "rectangle",
        "title": "今の体調を天気で表すと？",
        "text": "選択してください：",
        "actions": [
            {
              "type": "postback",
              "label": "☀️",
              "data": "sunny"
            },
            {
              "type": "postback",
              "label": "☁️",
              "data": "cloudy"
            },
            {
              "type": "postback",
              "label": "🌧",
              "data": "rainy"
            }
        ]
      }
    }
    client = Line::Bot::Client.new { |config|
      config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
      config.channel_token = ENV["LINE_CHANNEL_TOKEN"]
    }
    client.push_message(user.line_user_id, message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/index.html.haml
%h1 Companies#index
%p Find me in app/views/companies/index.html.haml

- @companies.each do |company|
  = company.name
  = company.company_code

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/show.html.haml
%h1 Pages#show
%p Find me in app/views/pages/show.html.haml

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', @post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%h1 Listing posts

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.name
        %td= link_to 'Show', post
        %td= link_to 'Edit', edit_post_path(post)
        %td= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @post.name

= link_to 'Edit', edit_post_path(@post)
\|
= link_to 'Back', posts_path

app/views/users/index.html.haml
%h1 Users#index
%p Find me in app/views/users/index.html.haml

- @users.each do |user|
  = user.name
  = user.status
  = user.line_user_id

  = link_to 'この人に質問を送る', user_path(user), method: :put
  %br